:title: 'Idealize!'
:routes:
  '/':
    :controller: HomeController
    :title: Home
    :description: Bem-vindo ao Idealize.
    :layout:
    :icon: home
    :navigation: [header, drawer, dashboard]
    :profiles: [usuario]

  '/ideias':
    :controller: IdeiasController
    :title: Ideias
    :description: Ideias criadas pelos colaboradores.
    :layout:
    :icon: wb_incandescent
    :navigation: [header, drawer]
    :profiles: [usuario]

  '/conta':
    :controller: ContaController
    :title: Conta
    :description: Administre sua conta.
    :layout:
    :icon: account_box
    :navigation: [menu]
    :profiles: [usuario]

  '/mensagens':
    :controller: MensagensController
    :title: Mensagens
    :description: Mensagens dos usuários para você.
    :layout:
    :icon: mail
    :navigation: [menu]
    :profiles: [usuario]

  '/usuarios':
    :controller: UsuariosController
    :title: Usuários
    :description: Usuários e (co)autores do Idealize.
    :layout: dashboard
    :icon: people
    :navigation: []
    :profiles: [usuario]

  '/administracao':
    :controller: AdministracaoController
    :title: Configurações
    :description: Configurações e ajustes.
    :layout: dashboard
    :icon: settings
    :navigation: [dashboard]
    :profiles: [administrador]

  '/categorias':
    :controller: CategoriasController
    :title: Categorias
    :description: Administração das categorias.
    :layout: dashboard
    :icon: group_work
    :navigation: [dashboard]
    :profiles: [administrador, moderador]

  '/moderacao':
    :controller: ModeracaoController
    :title: Moderação
    :description: Moderação das ideias.
    :layout:
    :icon: assignment
    :navigation: [dashboard]
    :profiles: [moderador]

  '/avaliacao':
    :controller: AvaliacaoController
    :title: Avaliação
    :description: Avaliação das ideias publicadas.
    :layout:
    :icon: assignment_turned_in
    :navigation: [dashboard]
    :profiles: [avaliador]

  '/relatorios':
    :controller: RelatoriosController
    :title: Relatórios
    :description: Relatórios das ideias e autores.
    :layout: dashboard
    :icon: assessment
    :navigation: [dashboard]
    :profiles: [administrador]

:pages:
  '/painel':
    :title: Painel de Controle
    :description: Painel de controle para administração.
    :data:
    :layout: dashboard
    :navigation: [menu]
    :profiles: [usuario]
    :icon: dashboard

  '/faq':
    :title: Dúvidas
    :description: Dúvidas frequentes sobre o Idealize.
    :data: faq
    :layout:
    :navigation: []
    :profiles: []
    :icon: help

  '/versao':
    :title: Versões
    :description: Histórico das modificações do Idealize
    :data: ../CHANGELOG
    :layout:
    :navigation: []
    :profiles: []
    :icon: info

:email:
  # :address: 'smtps.expresso.am.gov.br'
  # :port: 587
  # :user_name:
  # :password:
  # :authentication: plain
  # :enable_starttls_auto: false
  # :openssl_verify_mode: none
  :address: smtp.expresso.am.gov.br
  :port: 25
  :domain: idealize.prodam.am.gov.br
