:title: 'Idealize!'
:routes:
  '/':
    :title: Home
    :controller: HomeController
    :navigation: sidebar
    :icon: home
  '/conta':
    :title: Conta
    :controller: AcessoController
    :navigation: toolbar
    :icon: account_box
  '/ideias':
    :title: Ideias
    :controller: IdeiasController
    :navigation: sidebar
    :icon: wb_incandescent
