:title: 'Idealize!'
:routes:
  '/':
    :controller: HomeController
    :title: Home
    :description: Bem-vindo ao Idealize.
    :navigation: [header, drawer]
    :profiles: []
    :icon: home
  '/ideias':
    :controller: IdeiasController
    :title: Ideias
    :description: Ideias criadas pelos colaboradores.
    :navigation: [header, drawer]
    :profiles: []
    :icon: wb_incandescent
  '/conta':
    :controller: AcessoController
    :title: Conta
    :description: Administre sua conta.
    :navigation: [top]
    :profiles: []
    :icon: account_box
  '/usuarios':
    :controller: UsuariosController
    :title: Usuários
    :description: Usuários e (co)autores do Idealize.
    :navigation: []
    :profiles: []
    :icon: people
  '/painel':
    :controller: PainelController
    :title: Painel de Controle
    :description: Painel de controle para administração.
    :navigation: [top]
    :profiles: []
    :icon: dashboard
    :routes:
      '/categorias':
        :controller: CategoriasController
        :title: Categorias
        :description: Administração das categorias.
        :icon: group_work
        :profiles: ['administrador', 'moderador']

:pages:
  '/faq':
    :title: Dúvidas
    :description: Dúvidas frequentes sobre o Idealize.
    :data: faq
    :navigation: [header, drawer]
    :profiles: []
    :icon: help
  '/versao':
    :title: Versões
    :description: Histórico das modificações do Idealize
    :data: ../CHANGELOG
    :navigation: []
    :profiles: []
    :icon: info
