:test: &default
  :debug: true
  :adapter: oracle
  :host: 10.20.1.175
  :port: 1521
  :database: oradds1.prodam.com.br
  :user: idealize
  :password: idealize2016
:development: *default
:stage: *default
:production:
  :debug: false
  :adapter: oracle
  :host: pdm1-prd-scan.prodam.local
  :port: 1521
  :database: idealize.prodam.com.br
  #:database: dbpdm01.prodam.com.br
  :user: idealize
  :password: Me#gh9fu
